### ISSUE TITLE
Upstream 'eos' improvements

### ISSUE THREAD

**Issue by ruslo** [elucideye/drishti#159]
Help with the https://github.com/patrikhuber/eos/issues/68 fix.

**Comment by headupinclouds** [comment]
https://github.com/hunter-packages/eos/tree/pr.eos.hunter.new : wip, waiting for :point_down:

WIP, requires:
* https://github.com/ruslo/hunter/issues/817 = eigen3-nnls
* https://github.com/ruslo/hunter/issues/816 = nanoflann
* hunter updates for above

**Comment by headupinclouds** [comment]
Updated to 12.0.1
