### ISSUE TITLE
[docs] 'drishti_add_test' peculiarities

### ISSUE THREAD

**Issue by ruslo** [elucideye/drishti#260]
* `drishti_test_main` is not `main` so there will be no default code returned. Users should be carefull with `s,main,drishti_test_main,g` substitution since missing return code will lead to undefined behavior
* Dependent libraries analyze happens in `drishti_test_main` function by reading according properties, hence all `target_link_libraries` must happens **before** `drishti_test_main` (dependency analyze feature need only for Android)

**Comment by headupinclouds** [comment]
This has been inactive for a long time.  Closing.  Issues can be migrated here as needed: https://github.com/hunter-packages/gauze/
