### ISSUE TITLE
investigate https://circleci.com (no build limits)

### ISSUE THREAD

**Issue by headupinclouds** [elucideye/drishti#295]
https://circleci.com/pricing/

They claim unlimited build limits, but it isn't clear if this pertains to individual session timeouts or not.  It could be an option for: Qt, OpenCV, Boost, etc.

Possible speed and stability improvements?

**Comment by headupinclouds** [comment]
I think circleci.com is worth a look to see if it could address the build timeout struggles (especially w/ Android).  The pre-baked Android images could solve a lot of the current android toolchain timeout problems:

* https://circleci.com/docs/1.0/android/
* https://circleci.com/docs/1.0/build-image-macos/
* https://circleci.com/docs/1.0/build-image-trusty/

**Comment by ruslo** [comment]
> The pre-baked Android images could solve a lot of the current android toolchain timeout problems

I don't think it will make difference for us since Android SDK managed by Hunter and Android emulator managed by Gauze.

**Comment by headupinclouds** [comment]
Closing.
