### ISSUE TITLE
Android CI tests w/ Emulator/QEMU

### ISSUE THREAD

**Issue by headupinclouds** [elucideye/drishti#351]
* https://github.com/ruslo/hunter/issues/663#issuecomment-277949562
* http://www.instructables.com/id/Creating-an-Android-Emulator-Using-Qemu/

Investigate running Android emulator CI tests using QEMU for HW emulation.  This would be a much easier near term path than using Amazon Device Farm.

**Comment by headupinclouds** [comment]
https://github.com/elucideye/drishti-upload/pull/72

**Comment by ruslo** [comment]
Fixed https://github.com/elucideye/drishti/pull/441
