### ISSUE TITLE
reference: ndk roadmap

### ISSUE THREAD

**Issue by headupinclouds** [elucideye/drishti#409]
>> https://github.com/android-ndk/ndk/issues/379#issuecomment-298755744

> libc++ is in much better shape than it was back then, but it's still not quite to the point that I'm comfortable recommending it. For a timeline on that, see our roadmap.

https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md

**Comment by xsacha** [comment]
NDK r17 is officially out with libc++ as default now.

**Comment by headupinclouds** [comment]
Thanks.  I see @ruslo has already added [android-ndk-r17-api-24-arm64-v8a-clang-libcxx14](https://github.com/ruslo/polly/blob/master/android-ndk-r17-api-24-arm64-v8a-clang-libcxx14.cmake) in @polly.  We can update the [r16b toolchain](https://github.com/elucideye/drishti/blob/542f721cab25ff7054d89704b4b5cb9f634d6b08/.travis.yml#L66) toolchain to r17.

Caveat: I tested a beta version or r17 and it didn't support `MinSizeRel` + `LTO` yet, although a `gcc` + `libc++` combination could be used as a workaround.

**Comment by headupinclouds** [comment]
testing https://github.com/elucideye/drishti/pull/656

**Comment by xsacha** [comment]
You'll need to use CMake 3.12 (unreleased) as well.

**Comment by ruslo** [comment]
> You'll need to use CMake 3.12 (unreleased) as well.

@xsacha CMake 3.11.1 works fine with Android NDK r17:
* https://travis-ci.org/ingenue/hunter/jobs/378884704

**Comment by xsacha** [comment]
Oh right. Some of my packages complain about FindThreads in NDK r17. Thought it would affect this project too.

**Comment by xsacha** [comment]
Also, Boost will fail to compile with NDK r17 if you target API 21,22,23. Only works on older APIs or 24 and above due to removal of libandroid_support.
See: https://github.com/android-ndk/ndk/issues/480#issuecomment-388977048

**Comment by headupinclouds** [comment]
Merged #656 ... Thanks.
