### ISSUE TITLE
Use Git submodules instead of release archives

### ISSUE THREAD

**Issue by ruslo** [elucideye/drishti#414]
Migrated from https://github.com/elucideye/drishti/issues/88

This is a variant of Git support in Hunter when instead of URL/SHA1 of sources we can specify GIT_REPO/SHA1 of commit. Commit can be taken from submodule of current project so user don't have to add SHA1 in `cmake/Hunter/config.cmake` himself. Effectively this is similar to having 3rd party injected by `add_subdirectory` however it have some important benefits:
- 3rd party options doesn't leak to the current project code, you don't have to do `option(SKIP_INSTALL "Avoid installation of submodule libraries" ON)`/`unset(SKIP_INSTALL CACHE)`
- 3rd party targets will be installed. It means that you don't have to deal with build/install interface of C++ includes (like `thread-pool-cpp/thread_pool.hpp` vs `thread_pool/thread_pool.hpp`)
- With submodules you can deal only with leaves of the dependency tree. It means if you have dependency `A (hunter) -> B (submodule) -> C (hunter)` you can't use `add_subdirectory(B)` because A from Hunter will use different version. You have to add A as a submodule too: `A (submodule) -> B (submodule) -> C (hunter)`:

``` cmake
hunter_add_package(C) # if needed by this project

add_subdirectory(3rdParty/B) # before A
add_subdirectory(3rdParty/A)
```

Related Hunter feature request: https://github.com/ruslo/hunter/issues/204

**Comment by ruslo** [comment]
> Related Hunter feature request: ruslo/hunter#204

This one seems pretty tricky, so my suggestion is to start with something simple like https://github.com/ruslo/hunter/issues/56. It's not optimal:
1. on change we will build package from scratch (`_builds` directory with artifacts not saved)
2. on change the `config-id` will be affected, hence every small change of package create new root directory

(2) can be optimized with cellar system feature: https://github.com/elucideye/drishti/issues/153

**Comment by ruslo** [comment]
> to start with something simple like ruslo/hunter#56

Actually I mean https://github.com/ruslo/hunter/issues/230

**Comment by headupinclouds** [comment]
This makes sense...

For reference, ruslo/hunter#230 ==
```
hunter_config(Foo GIT_SUBMODULE) # Allow getting GIT_SHA1 from submodule
hunter_config(Foo GIT_SHA1 xxx GIT_REPO https://.../Foo.git) # Allow SHA1 of commit of git repo:
```

**Comment by ruslo** [comment]
Fixed
