### ISSUE TITLE
edit CI toolchains

### ISSUE THREAD

**Issue by headupinclouds** [elucideye/drishti#455]
Limit Travis to 5 jobs (can avoid both Debug & Release Xcode+ASAN) and avoid long 3x {armv7, armv7a, arm64} iOS builds (arm64 is ok for day-to-day):
* add ios-nocodesign-10-1-arm64-dep-9-0-device-libcxx-hid-sections-lto
* remove Debug or Release variant of address sanitizer osx-10-12-sanitize-address-hid-sections

**Comment by headupinclouds** [comment]
os-nocodesign-10-1-arm64-dep-9-0-device-libcxx-hid-sections-lto -> PR # https://github.com/ruslo/polly/pull/147

**Comment by ruslo** [comment]
> PR # ruslo/polly#147

Merged

**Comment by headupinclouds** [comment]
Thanks.  Done.  #464.  In the future, CMake LTO customization that supports optional LTO for the various test, console and sample apps might help (w/ cmake LTO customization in the future).  LTO is most critical for the deployed library assets.
