### ISSUE TITLE
Android device emulator with GPU

### ISSUE THREAD

**Issue by ruslo** [elucideye/drishti#468]

**Comment by ruslo** [comment]
Update config:
* https://github.com/elucideye/drishti/blob/6f76a22568abf205b6fe2d739184118257af84f4/src/lib/drishti/CMakeLists.txt#L234-L237

**Comment by ruslo** [comment]
The tests should be checking these two conditions to enable GPU code:

```cmake
if ((TARGET drishti_gltest) AND DRISHTI_BUILD_OGLES_GPGPU)
  target_link_libraries(${test_app} PUBLIC drishti_gltest)
  target_compile_definitions(${test_app} PUBLIC DRISHTI_ACF_DO_GPU=1)
  if(DRISHTI_BUILD_QT)
    target_compile_definitions(${test_app} PUBLIC DRISHTI_BUILD_QT=1)
  endif()
endif()
```

**Comment by ruslo** [comment]
I'm testing `DrishtiACFTest` on my local Linux machine now.

We have few options for GPU while starting emulator, see:
* https://developer.android.com/studio/run/emulator-acceleration.html#command-gpu

Test results:
* `-gpu auto` (fail)
* `-gpu host` (pass)
* `-gpu mesa` (pass)
* `-gpu angle` (windows only)
* `-gpu swiftshader` (fail)
* `-gpu off` (fail)

**Comment by ruslo** [comment]
> -gpu host (pass)

* https://travis-ci.com/elucideye/drishti/builds/47731350

> -gpu mesa (pass)

* https://travis-ci.com/elucideye/drishti/builds/47731179

**Comment by headupinclouds** [comment]
For CI builds I think we will need `-gpu mesa`, as there will be no host GPU available.  This will give us some test coverage for remote mobile CI testing.  Let's make that the default emulator setting when `DRISHTI_CI == ON`.  

Then we can change this:

```
if(NOT ${DRISHTI_CI})
  add_subdirectory(gltest)
endif()
```

to this:

```
# Android emulator supports GPU use
if(ANDROID OR NOT ${DRISHTI_CI})
  add_subdirectory(gltest)
endif()
```

That leaves iOS and "desktop" support for CI builds.

**Comment by ruslo** [comment]
Travis logs are mess... can't get it working properly. Either it's hidden because more than 10'000 lines printed or  "No output has been received in the last 10m0s" because output is not verbose.

Raw log link returns no information at all, only 5 first lines:
```
Worker information
hostname: wjb-2:49cde7b0-fa19-4849-8a85-9855d008835b
version: v2.6.2 https://github.com/travis-ci/worker/tree/fdccca4efd347ebc889baae641ccbf55bb871d19
instance: fa9285e0-08ce-4e83-a4ce-480f197648c8:travis-ci-osx10.11-xcode7.3-1480691248
startup: 2m5.788436592s
```

**Comment by ruslo** [comment]
> For CI builds I think we will need -gpu mesa

```
ERROR: Invalid GPU mode 'mesa', use one of: on off host guest
```

**Comment by ruslo** [comment]
Result for `-gpu host`:
```
5: Done
 5/14 Test  #5: DrishtiACFTest ........................   Passed  125.83 sec
```

**Comment by ruslo** [comment]
Fixed by https://github.com/elucideye/drishti/pull/472
