### ISSUE TITLE
Test fat LTO files build time

### ISSUE THREAD

**Issue by ruslo** [elucideye/drishti#469]
- [ ] GCC LTO Linux
- [ ] GCC LTO Android

CI:
* https://travis-ci.com/elucideye/drishti/builds/46210564

Pull request:
* https://github.com/elucideye/drishti/pull/447

Original issue:
* https://github.com/elucideye/drishti/issues/445

**Comment by ruslo** [comment]
> GCC LTO Linux

Hit weird error with `-flto -ffat-lto-objects` toolchain. Linker complains about undefined symbol:
```
/.../Install/lib/libX11.a(CrCursor.o): In function `XCreatePixmapCursor':
CrCursor.c:(.text.XCreatePixmapCursor+0x2a): undefined reference to `_XTryShapeBitmapCursor'
```

However symbol defined in the same library:

```
> nm --demangle /.../Install/lib/libX11.a

CrCursor.o:
0000000000000000 T XCreatePixmapCursor
                 U _XGetRequest
                 U _XTryShapeBitmapCursor <<<<<<<<< undefined

CrGlCur.o:
0000000000000000 T _XNoticeCreateBitmap
0000000000000000 T _XNoticePutBitmap
0000000000000000 T _XTryShapeBitmapCursor <<<<<<<<< defined
                 U _XUnlockMutex_fn
```

Need to try another GCC version, probably it's a bug. Some similar executables
before links fine.

**Comment by ruslo** [comment]
> Need to try another GCC version, probably it's a bug

```
> /usr/bin/g++-7 --version
g++-7 (Ubuntu 7.1.0-5ubuntu2~16.04) 7.1.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

> cat boo.cpp
int boo() {
  return 0x42;
}

> /usr/bin/g++-7 boo.cpp -o boo.o -c

> /usr/bin/gcc-ar-7 cr libboo.a boo.o
[1]    5605 segmentation fault (core dumped)  /usr/bin/gcc-ar-7 cr libboo.a boo.o
```

Interestingly enough that this works:

```
> which gcc-ar-7
/usr/bin/gcc-ar-7

> gcc-ar-7 cr libboo.a boo.o
> echo $?
0
```

But CMake use full path...

**Comment by ruslo** [comment]
I've build GCC 7.1.0 from sources and it works well. I've build Drishti twice, build time for `-flto -ffat-lto-objects` with disabled LTO for tests is quite the same as for the `-flto -fno-fat-lto-objects`: is about 49 minutes. I guess it means that `DRISHTI_EXE_IPO` option will not help.

**Comment by headupinclouds** [comment]
Thanks.  The single architecture LTO builds are workable enough.  We can switch back to non-lto toolchains if this becomes too much of a bottleneck for PR testing.
