### ISSUE TITLE
iris ellipse regression

### ISSUE THREAD

**Issue by kingvision** [elucideye/drishti#490]
Hi:
    would you provide an example for iris ellipse regression?
    and how to prepare input data.

thanks

**Comment by headupinclouds** [comment]
You can take a look at the CMake unit test configuration for the `drishti::eye::EyeModelEstimator` class for sample input and output [here](https://github.com/elucideye/drishti/blob/master/src/lib/drishti/eye/ut/CMakeLists.txt#L8-L16)

That will be run by default with the `--test` option provided in your `polly.py` script.

It will give you a sense of a typical input image, expected output, and the default model/archive.  I will post another sample video showing typical eye tracking with a standard "selfie" video from an iPhone or Android device.

For processing on the terminal, you can use this application:

https://github.com/elucideye/drishti/blob/master/src/app/eye/eye.cpp

It should be installed by default after you run a `polly.py` build command (w/ `--install`).  The apps will be located in `${DRISHTISDK}/_install/<toolchain>/_bin`.  If the application is in your path, you can simply type `drishti-eye` and it should show you a help message.

It might look something like: `drishti-eye --input=some_file.png --output=some/output/directory --model=path/to/drishti_eye_full_npd_eix.cpb -j -a -r`.  That will dump estimated eye models in JSON format along with an annotated image (a wireframe eye model overlay).  Note that `-r` or `-l` must be specified for (r)right or (l)eft eye of the subject (i.e., not in the coordinate system of the image -- a (r)right eye is on the left side of a standard full face image).  The input images must have a 4:3 aspect ratio, with some small amount of padding.  You can query the mean training sample from the `drishti::eye::EyeModelEstimator` class once a model is loaded for a more precise target input, but the sample eye crop from the unit test should be a good guide.  It will attempt minimal padding to achieve a 4:3 aspect ratio if needed.

The provided model is targeting visible wavelength RGB input images at fairly low resolution.
