### ISSUE TITLE
Helper for `-framework`

### ISSUE THREAD

**Issue by ruslo** [elucideye/drishti#504]
Use pseudo-package to apply `-framework ...` linker flags.

**Comment by ruslo** [comment]
- [ ] ogles_gpgpu
- [ ] aglet
- [ ] drishti

**Comment by ruslo** [comment]
> spdlog (android and iOS)

Fixed by https://github.com/elucideye/drishti/pull/505.

I can't reproduce error on iOS so keep this part as is. If error occurs `pkg.foundation` can be used:
* https://github.com/ruslo/hunter/wiki/pkg.foundation

**Comment by headupinclouds** [comment]
> I can't reproduce error on iOS 

Ok.  I think my comments were misleading.  I wasn't sure about `iOS` dependencies exactly.

**Comment by headupinclouds** [comment]
Thanks.
