### ISSUE TITLE
A new release is required to match the new cpb model

### ISSUE THREAD

**Issue by saturosfz** [elucideye/drishti#526]
I failed to load the new cpb model, and according to commit comment the new model works better, so would you mind giving a new release?

**Comment by headupinclouds** [comment]
The latest code (HEAD from master) will be compatible with the updated archives if you build from source.  If not, there will be a tagged release sometime in the next few days when the project is added to the hunter package manager.

**Comment by saturosfz** [comment]
It seems that you have a CI system. Could you release the build result? I've always failed to build the project under windows:(

**Comment by headupinclouds** [comment]
Yes, I plan to tag a release this week once the final hunter mods are in place.  What compiler are you using on Windows, btw?  If it is C++11 (>= vs-14-2015 I think) we should be able to get it to work.  Feel free to post build details.

**Comment by headupinclouds** [comment]
>  Could you release the build result?

Please try the latest release: https://github.com/elucideye/drishti/releases/tag/v0.8.5

> I've always failed to build the project under windows:(

Some build instructions have been added on the README that should clarify the build process.
