### ISSUE TITLE
portable filesystem module

### ISSUE THREAD

**Issue by headupinclouds** [elucideye/drishti#602]
This is currently used for portable boost::filesystem::path() manipulation and (de)construction

There is some value in replacing this with something lighter weight for portable path construction.
* c++17 provides this (can bump language standard when ndk17 is ready)
* home brew something (testing is time consuming due to multi-platform nature)
* https://github.com/hallsoftware/Cpp-Filesystem-Lite
* https://github.com/aptakhin/crefile
* https://github.com/wjakob/filesystem
* https://github.com/srand/stdext-path

All the simple header only boost alternatives don't seem to be actively maintained, and there won't be a need for these when using c++17.

**Comment by headupinclouds** [comment]
Hunter PR with initial https://github.com/srand/stdext-path package for path manipulation testing

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/commit/2c8e1475c9f5ebde57ecf0fab599fbb3c3ad4531
