### ISSUE TITLE
Upload improvement

### ISSUE THREAD

**Issue by ruslo** [elucideye/drishti#608]

**Comment by headupinclouds** [comment]
After uploading binaries from drishti (via hunter extensions) the drishti <-> drishti-upload roles can be reversed.  drishti will resume control over the config.cmake file, drishti-upload will become optional (for one touch cache updates), and it will maintain drishti as a submodule.

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/issues/1097
