### ISSUE TITLE
Ubuntu 16.04 Exception caught

### ISSUE THREAD

**Issue by dyciel93** [elucideye/drishti#667]
I tried to run the following code 

"~/Downloads/drishti/_builds/cxx11/src/app/hci$ ./drishti-hci --factory=/home/william/Downloads/drishti-assets/drishti_assets_full.json --input=/home/william/Downloads/test.avi --focal-length=500 --min=0.5 --max=1.0 --output=/tmp/ --calibration=0.002 --scale=1.2 --window --resolution=0.5"

However I get the following error

Exception caught: OpenCV(3.4.1) /home/william/Downloads/drishti/src/app/videoio/VideoSourceCV.cpp:118: error: (-215) false in function create

**Comment by headupinclouds** [comment]
That error is coming from a simple VideoSourceCV that is used for both continuous process and random access (batch processing) for mixed images.   It doesn't currently know anything about `*.avi` format but you can pass `--cv` 

see : https://github.com/elucideye/drishti/blob/f0f5a9c629616b2a5f47ab6b344912e856cdc0bb/src/app/hci/hci.cpp#L201

And it will try to open it directly with the standard `cv::VideoCapture` , see:

https://github.com/elucideye/drishti/blob/f0f5a9c629616b2a5f47ab6b344912e856cdc0bb/src/app/hci/hci.cpp#L331-L349

So you could try `--input=/home/william/Downloads/test.avi --cv`.

I can make the exception more informative.

If you are testing on a desktop you could use `drishti_assets_big.json`.

**Comment by dyciel93** [comment]
Hello, thank you very much for your advice. After, I've added the --cv, I get the following error "(DEBUG) try_init_v4l2 VIDIOC_QUERYCAP "/home/william/Downloads/test.avi": Inappropriate ioctl for device

**Comment by headupinclouds** [comment]
The OpenCV build doesn't support the `AVI` codec required for that video --  at least not on your platform with the current configuration.  This is related to the OpenCV `videoio` and `highgui` modules.  OpenCV has a long list of configuration options which may or may not help address the issue.

The customization is performed in the submodule config here `src/examples/drishti-upload/config.cmake`:

https://github.com/elucideye/drishti-upload/blob/167387de283c34175acb6cef8839a54f5fe5ab03/config.cmake#L22-L162

You can always experiment with changing the build arguments on your own.

More information on OpenCV codecs and the `videoio` module can be found here:

https://docs.opencv.org/3.4/d0/da7/videoio_overview.html

A quick search for "try_init_v4l2 VIDIOC_QUERYCAP" gets a few hits on SO, including this one:
 
https://stackoverflow.com/a/45893821

It seems you may need to use an ffmpeg back end for this.  That isn't currently available in Hunter, but you can try adding it as a local package on your system.  You will need

```
WITH_FFMPEG=ON         # "Include FFMPEG support"
```

In the `config.cmake` shown above.
