### ISSUE TITLE
Tracking the pupil position

### ISSUE THREAD

**Issue by dyciel93** [elucideye/drishti#679]
I'm trying to make a pupil position detector using the code. I have been looking into hci.cpp code as a reference. However, I can't seem to find a way to extract any data on the position of the green crosshairs that are generated in the hci application. Any tips and advice will be appreciated.
Thank you. @ #

**Comment by headupinclouds** [comment]
The iris center is probably most stable for these models.  You could check that here:

https://github.com/elucideye/drishti/blob/452182a2c1e9070dcde2847a57ab93e191f7ddb7/src/app/hci/hci.cpp#L79

```
for(const auto &f : faces)
{
     const std::array<cv::Point2f,2> eyeCenters{ { face.eyeFullR->irisEllipse.center, face.eyeFullL->irisEllipse.center } };
}
```

**Comment by dyciel93** [comment]
Thank you very much. I don't understand the last bit of the code

`for(const auto &f : faces)
{
     const std::array<cv::Point2f,2> eyeCenters{ { face.eyeFullR->irisEllipse.center, face.eyeFullL->irisEllipse.center } };
}`

Could you please explain this to me?
I would like to just print out the x coordinates of the pupil locations
Thank you very much.

**Comment by headupinclouds** [comment]
```

**Comment by dyciel93** [comment]
Hey I tried the code, but I'm getting the following errors

`no member named 'eyeFullR' in
      'drishti::hci::FaceMonitor::FaceImage'`

May I know which place I should be putting this in?

Thank you very much!

**Comment by headupinclouds** [comment]
Closing
