### ISSUE TITLE
can't parse window path separator in toolchain.cmake:56

### ISSUE THREAD

**Issue by ygyin-ivy** [elucideye/drishti#715]
i import facefilter to android studio in platform  window.
auto-generated facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/generated/toolchain.cmake:56
cant parse windot path, 
such as `C:\Users\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake`
i want to  add  a line
```
    string(REPLACE "\\" "/" outputVar ${_inputVar})
```

before line 56. but  i dont know which cmake in where generate this toolchain.cmake

it is a bug before cmake 3.7.1？ i know i should use cmake 3.7.1 or later

**Comment by headupinclouds** [comment]
Thanks for reporting this.  I don't think the most recent Android Studio application stuff has been tested on Windows yet.  It may need a patch or two.  It would be nice to get this working.  I'll share a few pointers about the process below that might help. In case you haven't already, please take a look at the most recent README (and links) for notes about the Android Studio specific details.

As you noted above, a recent CMake is required, and has to be specified in the `local.properties` file for the project.  There is a toolchain *injection* that takes place early in the build to enable Hunter based on this template [toolchain.cmake.in](https://github.com/elucideye/drishti/blob/master/src/examples/cmake/template/toolchain.cmake.in) template file.  The injection takes place in the early stages of the project CMake in [init.cmake](https://github.com/elucideye/drishti/blob/588cea284904f6640d34ec56522d734319903e87/src/examples/cmake/include/init.cmake#L3-L11).

I beveled you could convert Windows `\` characters to CMake `/` characters in an `if(MSVC)` block here:

https://github.com/elucideye/drishti/blob/588cea284904f6640d34ec56522d734319903e87/src/examples/cmake/template/toolchain.cmake.in#L60

Please share any notes you find so we can update the project here if necessary.  If you don't find a fix I can probably take a look on a Windows host later this week.

**Comment by ruslo** [comment]
> i know i should use cmake 3.7.1 or later

It's 3.9.2 actually: https://github.com/elucideye/drishti#android-studio-build

I'm testing the fix, you can check this branch:
* https://github.com/elucideye/drishti/tree/pr.android.windows

**Comment by ruslo** [comment]
> I'm testing the fix, you can check this branch

Fix merged to master: https://github.com/elucideye/drishti/pull/717

I have tested it on my Windows machine, Android Studio build/launch works fine.

**Comment by ygyin-ivy** [comment]
thx

**Comment by headupinclouds** [comment]
Thanks.  Closing.
