### ISSUE TITLE
mac os/android studio build error

### ISSUE THREAD

**Issue by imerse** [elucideye/drishti#745]
hi~ I tried to compile the facefilter demo, and occurred this error. 
What I have tried:
Import drishti/android-studio into android studio, sysc passed, then make project, it came out the error below:  
my environment:

> mac os mojave v10.14
> cmake version 3.13.0
> ninja version 1.9.0
> android studio 3.3

> Error configuring CMake server (/usr/local/bin).
HUNTER_RUN_UPLOAD: OFF
[hunter *** DEBUG *** 2019-02-18T14:44:57] HUNTER_ROOT set using HOME environment variable
[hunter *** DEBUG *** 2019-02-18T14:44:57] HUNTER_ROOT: /Users/imerse/.hunter
[hunter *** DEBUG *** 2019-02-18T14:44:57] Settings (initialize):
[hunter *** DEBUG *** 2019-02-18T14:44:57]   HunterGate done (NO)
[hunter *** DEBUG *** 2019-02-18T14:44:57]   Cache init (NO)
Android: Targeting API '24' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain ''
Check for working C compiler: /Users/imerse/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
Check for working C compiler: /Users/imerse/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- broken
CMake Error at /usr/local/Cellar/cmake/3.13.0/share/cmake/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/Users/imerse/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/local/bin/ninja" "cmTC_c1de8"
    [1/2] Building C object CMakeFiles/cmTC_c1de8.dir/testCCompiler.c.o
    [2/2] Linking C executable cmTC_c1de8
    FAILED: cmTC_c1de8 
    : && /Users/imerse/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=aarch64-none-linux-android24 --gcc-toolchain=/Users/imerse/Library/Android/sdk/ndk-bundle/toolchains//prebuilt/darwin-x86_64 --sysroot=/Users/imerse/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections CMakeFiles/cmTC_c1de8.dir/testCCompiler.c.o  -o cmTC_c1de8  -latomic -lm && :
    ld: unknown option: --sysroot=/Users/imerse/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ninja: build stopped: subcommand failed.
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:18 (project)

Configuring incomplete, errors occurred!
See also "/Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".
See also "/Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeError.log".

**Comment by imerse** [comment]
I tried according to the guide in [readme.rst](https://github.com/elucideye/drishti#android-studio-build) 
`[drishti/android-studio]> ./gradlew assembleDebug`
 the same error occurred like before.

`[drishti/android-studio]> cmake --build ../src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a`
this one will cause 
```
➜  android-studio git:(master) cmake --build ../src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a
ninja: error: loading 'build.ninja': No such file or directory
```

**Comment by ruslo** [comment]
What Android NDK version you're using?

**Comment by imerse** [comment]
> What Android NDK version you're using?

```
➜  ndk-bundle cat source.properties
Pkg.Desc = Android NDK
Pkg.Revision = 19.1.5304403
```

**Comment by headupinclouds** [comment]
The NDK r19 default toolchain introduced some breaking changes with the internal CMake Android support.

There is an initial branch with some workarounds here:

https://github.com/elucideye/drishti/tree/pr.ndk.r19

https://github.com/elucideye/drishti/commit/f0088830cf2908b0063bd8b5138520cb5b4607fc

Based on https://github.com/android-ndk/ndk/issues/890

**Comment by imerse** [comment]
> Based on [android-ndk/ndk#890](https://github.com/android-ndk/ndk/issues/890)

Thanks at first. It seems worked. I tried to build based on the `pr.ndk.r19` branch, but it stuck here as below.

![image](https://user-images.githubusercontent.com/8415005/53094934-69cccd80-3556-11e9-9a2a-2129228163e3.png)

with no error log.

**Comment by headupinclouds** [comment]
I managed to get through a build a couple of weeks ago with r19, but the CI builds in the PR I posted are currently failing.  The android builds have always been a little tricky due to some known bugs in the gradle + cmake-server interaction.  Sorry about that.  See @ruslo 's comments.  I'll try to spend some more time with it, although r19 support might be ill advised based on his comments.

**Comment by headupinclouds** [comment]
If you downgrade to r18 it should work as is.

```
cat drishti/android-studio/local.properties
```

You can specify this explicitly in the local.properties file:

```
# Use latest default/bundled NDK
#ndk.dir=/Users/username/Library/Android/sdk/ndk-bundle

# Use NDK r18b instead
ndk.dir=/Users/username/android/android-ndk-r18b
sdk.dir=/Users/username/Library/Android/sdk
cmake.dir=/usr/local
```

**Comment by imerse** [comment]
Yeah, I downgraded to r18b,  and changed the local.properties file.
I run sync in the android studio it still stuck. But it was not the same place.
![image](https://user-images.githubusercontent.com/8415005/53152385-5d954e80-35f0-11e9-9f04-42e7bdbbd51e.png)

I tried change `if(DRISHTI_DEBUG_STOP) with if(TRUE)` and run `./gradlew assembleDebug`,  it shows build success. Then I change `if(TRUE) with if(DRISHTI_DEBUG_STOP)` back.  After that, the command `[drishti/android-studio]> cmake --build ../src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a` stuck again.

➜  android-studio git:(master) ✗ cmake --build ../src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a

[0/1] /usr/local/Cellar/cmake/3.13.0/bin/cmake -S/Users/imerse/projects/python/kaiyuan/drishti -B/Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a
HUNTER_RUN_UPLOAD: OFF
-- [hunter *** DEBUG *** 2019-02-21T14:07:29] HUNTER_ROOT set using HOME environment variable
-- [hunter *** DEBUG *** 2019-02-21T14:07:29] HUNTER_ROOT: /Users/imerse/.hunter
-- [hunter *** DEBUG *** 2019-02-21T14:07:30] Settings (initialize):
-- [hunter *** DEBUG *** 2019-02-21T14:07:30]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2019-02-21T14:07:30]   Cache init (YES)
CMAKE_INSTALL_PREFIX: /usr/local
-- [hunter *** DEBUG *** 2019-02-21T14:07:30] Single-configuration generator
-- [hunter *** DEBUG *** 2019-02-21T14:07:30] List of cache servers:
-- [hunter *** DEBUG *** 2019-02-21T14:07:30]   * https://github.com/elucideye/hunter-cache
-- [hunter *** DEBUG *** 2019-02-21T14:07:30] Settings (finalize):
-- [hunter *** DEBUG *** 2019-02-21T14:07:30]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2019-02-21T14:07:30]   Cache init (YES)
-- [hunter *** DEBUG *** 2019-02-21T14:07:30] Variables from HunterGate:
-- [hunter *** DEBUG *** 2019-02-21T14:07:30]   HUNTER_GATE_ROOT: /Users/imerse/.hunter
-- [hunter *** DEBUG *** 2019-02-21T14:07:30]   HUNTER_GATE_VERSION: 0.23.14
-- [hunter *** DEBUG *** 2019-02-21T14:07:30]   HUNTER_GATE_SHA1: f58bcf274f29097ac380bfe4955d2a66f077e741
-- [hunter] Calculating Toolchain-SHA1
-- [hunter *** DEBUG *** 2019-02-21T14:07:30] [/Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/_3rdParty/Hunter/toolchain] > "/usr/local/Cellar/cmake/3.13.0/bin/cmake" "-DTOOLCHAIN_INFO_FILE=/Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/_3rdParty/Hunter/toolchain/toolchain.info.NOLF" "-DCMAKE_TOOLCHAIN_FILE=/Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/generated/toolchain.cmake" "-DHUNTER_SELF=/Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked" "-GNinja" "-H/Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/_3rdParty/Hunter/toolchain" "-B/Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/_3rdParty/Hunter/toolchain/_builds" "-DCMAKE_MAKE_PROGRAM=/usr/local/bin/ninja" "-DCMAKE_RELEASE_POSTFIX=" "-DCMAKE_DEBUG_POSTFIX=d"
-- Android: Targeting API '24' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
-- Android: Selected Clang toolchain 'aarch64-linux-android-clang' with GCC toolchain 'aarch64-linux-android-4.9'
-- Check for working C compiler: /Users/imerse/android/android-ndk-r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/imerse/android/android-ndk-r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/imerse/android/android-ndk-r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Check for working CXX compiler: /Users/imerse/android/android-ndk-r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/imerse/projects/python/kaiyuan/drishti/src/examples/facefilter/android-studio/app/.externalNativeBuild/cmake/debug/arm64-v8a/_3rdParty/Hunter/toolchain/_builds
-- [hunter *** DEBUG *** 2019-02-21T14:07:32] Already exists: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/toolchain.info
-- [hunter] Calculating Config-SHA1
>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>: /Users/imerse/projects/python/kaiyuan/drishti/src/examples/drishti-upload/cmake/Modules;/Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/modules;/Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/find;/Users/imerse/projects/python/kaiyuan/drishti/cmake/Modules <:<:<:<:<:<:<:<:<:<:<:<:<:<:<:<:<:<:<:<:<:<:<:
-- config.cmake --
  MSVC:
  APPLE:
  ANDROID: 1
  IOS:
  is_linux: 0
  XCODE:
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Cache data is up-to-date
-- [hunter] HUNTER_ROOT: /Users/imerse/.hunter
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] HUNTER_TOOLCHAIN_ID_PATH: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] HUNTER_CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] HUNTER_BUILD_SHARED_LIBS:
-- [hunter] [ Hunter-ID: f58bcf2 | Toolchain-ID: 4e02b95 | Config-ID: 7031e6f ]
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/check_ci_tag/hunter.cmake
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] check_ci_tag versions available: [1.0.0]
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package 'check_ci_tag' CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package 'check_ci_tag' is cacheable: YES
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Install to: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install
-- [hunter] CHECK_CI_TAG_ROOT: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install (ver.: 1.0.0)
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package already installed: check_ci_tag
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/check_ci_tag/hunter.cmake ... end
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/drishti_assets/hunter.cmake
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] drishti_assets versions available: [1.6;1.7;1.8]
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package 'drishti_assets' CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package 'drishti_assets' is cacheable: YES
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Install to: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install
-- [hunter] DRISHTI_ASSETS_ROOT: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install (ver.: 1.8)
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package already installed: drishti_assets
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/drishti_assets/hunter.cmake ... end
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/drishti_faces/hunter.cmake
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] drishti_faces versions available: [1.1;1.2]
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package 'drishti_faces' CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package 'drishti_faces' is cacheable: YES
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Install to: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install
-- [hunter] DRISHTI_FACES_ROOT: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install (ver.: 1.2)
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package already installed: drishti_faces
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/drishti_faces/hunter.cmake ... end
-- Performing Test HAVE_THREAD_LOCAL_STORAGE_CPP11
-- Performing Test HAVE_THREAD_LOCAL_STORAGE_CPP11 - Success
DRISHTI_HAVE_THREAD_LOCAL_STORAGE : 1
CMAKE_CXX_COMPILER /Users/imerse/android/android-ndk-r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
CMAKE_C_COMPILER /Users/imerse/android/android-ndk-r18b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
** -- ** -isystem /Users/imerse/android/android-ndk-r18b/sysroot/usr/include/aarch64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -Wno-c++11-narrowing -Wno-unused-parameter -Wno-unused-local-typedefs -Wno-unknown-attributes -Wno-shorten-64-to-32
** -- ** -O2 -DNDEBUG
** -- ** -O0 -fno-limit-debug-info
+++  +++
--- Debug ---
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/sugar/hunter.cmake
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] sugar versions available: [1.3.0]
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package 'sugar' CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package 'sugar' is cacheable: YES
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Install to: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install
-- [hunter] SUGAR_ROOT: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install (ver.: 1.3.0)
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] Package already installed: sugar
-- [hunter *** DEBUG *** 2019-02-21T14:07:33] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/sugar/hunter.cmake ... end
-- [hunter *** DEBUG *** 2019-02-21T14:07:34] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/OpenCV/hunter.cmake
-- [hunter *** DEBUG *** 2019-02-21T14:07:34] OpenCV versions available: [3.4.1-p1;3.4.1-p0;3.4.0-p0;3.3.1-p1;3.3.1-p0;3.3.0-p2;3.3.0-p0;3.2.0-p2;3.2.0-p1;3.2.0-p0;3.1.0-p3;3.1.0-p2;3.1.0-p1;3.1.0-p0;3.0.0-p11;3.0.0-p10;3.0.0-p9;3.0.0-p8;3.0.0-p7;3.0.0-p6;3.0.0-p5;3.0.0-p4;3.0.0-p3;3.0.0-p2;3.0.0-p1;3.0.0-p0;3.0.0-rc1-p0;3.0.0-beta-p2;3.0.0-beta;2.4.11-p1;2.4.11;2.4.10]
-- [hunter *** DEBUG *** 2019-02-21T14:07:34] Package 'OpenCV' CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2019-02-21T14:07:34] Package 'OpenCV' is cacheable: YES
-- [hunter *** DEBUG *** 2019-02-21T14:07:34] Install to: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install
-- [hunter] OPENCV_ROOT: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install (ver.: 3.4.1-p1)
-- [hunter *** DEBUG *** 2019-02-21T14:07:34] Package already installed: OpenCV
-- [hunter *** DEBUG *** 2019-02-21T14:07:34] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/OpenCV/hunter.cmake ... end
-- Found OpenCV: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install (found version "3.4.1")
OpenCV_INCLUDE_DIRS = /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install/sdk/native/jni/include;/Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install/sdk/native/jni/include/opencv
OpenCV_LIB_DIR =
OpenCV_LIBRARIES = opencv_world
OpenCV_LIB_COMPONENTS = opencv_calib3d;opencv_core;opencv_features2d;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_objdetect;opencv_photo;opencv_video;opencv_videoio;opencv_videostab;opencv_world
OpenCV_LIBS = opencv_world
/Users/imerse/projects/python/kaiyuan/drishti/src/examples/drishti-upload/cmake/Modules;/Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/modules;/Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/find;/Users/imerse/projects/python/kaiyuan/drishti/cmake/Modules;/Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install/cmake/module
-- [hunter *** DEBUG *** 2019-02-21T14:07:34] load: /Users/imerse/.hunter/_Base/Download/Hunter/0.23.14/f58bcf2/Unpacked/cmake/projects/acf/hunter.cmake
-- [hunter *** DEBUG *** 2019-02-21T14:07:35] acf versions available: [0.0.1;0.0.2;0.1.3;0.1.13;0.1.14]
-- [hunter *** DEBUG *** 2019-02-21T14:07:35] Package 'acf' CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2019-02-21T14:07:35] Package 'acf' is cacheable: YES
-- [hunter *** DEBUG *** 2019-02-21T14:07:35] Install to: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install
-- [hunter] ACF_ROOT: /Users/imerse/.hunter/_Base/f58bcf2/4e02b95/7031e6f/Install (ver.: d1f681d6e678fcc45777e780f40fc196aad4c726)
-- [hunter *** DEBUG *** 2019-02-21T14:07:35] Locking directory: /Users/imerse/.hunter/_Base/Download/acf/d1f681d6e678fcc45777e780f40fc196aad4c726/d1f681d

**Comment by imerse** [comment]
By the way,I have checked out to master. This is the stuck-view:
![image](https://user-images.githubusercontent.com/8415005/53152722-4dca3a00-35f1-11e9-8863-ae810b2cbf1f.png)

**Comment by ruslo** [comment]
@imerse Please make sure other cmake instances are not running, if so - kill them and run build again. It's a known CMake + Android Studio issue:
- https://docs.hunter.sh/en/latest/faq/android-studio.html#detached-cmake

**Comment by imerse** [comment]
Thanks so much. It works! Although I don't know whether I have opened  several instances. I just restart the computer and run again, it works!
